name: Postman

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Start server using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d  # Adjust to your docker-compose file if necessary

      - name: Wait for the server to be ready
        run: |
          until curl -s http://localhost:8080/health; do
            echo "Waiting for server to be ready..."
            sleep 5
          done

      - name: Install Newman
        run: npm install -g newman
      - name: Run Postman Collection
        run: |
          newman run path/to/your/collection.json --env-var BASE_URL=http://localhost:8080
      - name: Stop and clean up Docker containers
        run: |
          docker-compose down