name: Build and Run Spring Boot Docker Compose

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven

    - name: Build Spring Boot application
      run: |
        ./mvnw clean package -DskipTests

    - name: Build Docker image
      run: |
        docker-compose -f docker-compose.yml build

    - name: Run Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d

    - name: Clean up containers
      run: |
        docker-compose -f docker-compose.yml down
