name: Build and Run Spring Boot Docker Compose

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Build Spring Boot application
        run: |
          mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          docker-compose -f docker-compose.yml build

      - name: Run Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
          action: "up"

      - name: Execute tests in the running services
        run: |
          docker compose exec test-app pytest

      - name: Clean up containers
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
          action: "down"
