name: Build and Run Spring Boot Docker Compose

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven

    - name: Build Spring Boot application
      run: |
        mvn clean package -DskipTests

    - name: Install Docker
      run: |
        sudo apt-get install -y docker.io

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build Docker image
      run: |
        docker-compose -f docker-compose.yml build

    - name: Run Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d

    - name: Clean up containers
      run: |
        docker-compose -f docker-compose.yml down
