name: Build and Run Spring Boot Docker Compose

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Build Spring Boot application
        run: |
          mvn clean package -DskipTests

      - name: Run Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
          action: "up"

      - name: Build and start Spring Boot app
        run: |
          docker-compose -f docker-compose.yml up -d springboot-app

      - name: Wait for Spring Boot app to be ready
        run: |
          echo "Waiting for Spring Boot app to start..."
          sleep 20

      - name: Run Postman tests with Newman
        run: |
          docker-compose -f docker-compose.yml run newman

      - name: Clean up containers
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
          action: "down"
